"""
3F-2A — Coarse CFO estimator characterization.

Diagnostic only.
No production files are modified.

Measures PacketDetector._estimate_coarse_cfo()
over a controlled CFO sweep using the actual STF
generated by the current waveform implementation.
"""

import numpy as np

import config as cfg
import waveform
from detector import PacketDetector


# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

CFO_LIST_HZ = [
    -200_000.0,
    -100_000.0,
    -50_000.0,
    -25_000.0,
    -10_000.0,
    -5_000.0,
    0.0,
    5_000.0,
    10_000.0,
    25_000.0,
    50_000.0,
    100_000.0,
    200_000.0,
]


# ------------------------------------------------------------
# Generate current STF from the actual waveform code
# ------------------------------------------------------------

stf = waveform.generate_stf().astype(np.complex64)

print("=" * 80)
print("3F-2A COARSE CFO ESTIMATOR CHARACTERIZATION")
print("=" * 80)

print()
print("CONFIGURATION")
print("-------------")
print(f"FS_FFT:       {cfg.FS_FFT}")
print(f"STF length:   {len(stf)}")
print(f"STF period:   16 samples")
print(f"STF repetitions: 8")

print()
print(
    f"Subcarrier spacing: "
    f"{cfg.FS_FFT / cfg.FFT_SIZE:.2f} Hz"
)

print()
print("CFO sweep:")
for cfo in CFO_LIST_HZ:
    print(f"  {cfo:10.1f} Hz")


# ------------------------------------------------------------
# CFO application
# ------------------------------------------------------------

def apply_cfo(signal, cfo_hz, fs_hz):

    n = np.arange(
        len(signal),
        dtype=np.float64,
    )

    phase = (
        2.0
        * np.pi
        * cfo_hz
        * n
        / fs_hz
    )

    return (
        signal
        * np.exp(1j * phase)
    ).astype(np.complex64)


# ------------------------------------------------------------
# Sweep
# ------------------------------------------------------------

detector = PacketDetector(
    fs=cfg.FS_FFT
)

print()
print("=" * 80)
print("RESULTS")
print("=" * 80)

print()
print(
    f"{'True CFO (Hz)':>15} "
    f"{'Estimated (Hz)':>18} "
    f"{'Error (Hz)':>15} "
    f"{'Error (%)':>12}"
)

print("-" * 80)

for true_cfo in CFO_LIST_HZ:

    stf_cfo = apply_cfo(
        stf,
        true_cfo,
        cfg.FS_FFT,
    )

    estimated = detector._estimate_coarse_cfo(
        stf_cfo
    )

    error = estimated - true_cfo

    if true_cfo != 0:
        error_pct = (
            100.0
            * error
            / abs(true_cfo)
        )
    else:
        error_pct = np.nan

    print(
        f"{true_cfo:15.1f} "
        f"{estimated:18.3f} "
        f"{error:15.3f} "
        f"{error_pct:12.3f}"
    )


print()
print("=" * 80)
print("3F-2A COMPLETE")
print("=" * 80)

print(
    "No production files were modified."
)